### PR TITLE
go db getting-started samples

### PR DESCRIPTION
**Pull request by jrperritt**

### CODE REVIEW

**Comment by jrperritt** [comment]
cc @jamiehannaford

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-6b5bcc7e0a/docs/)

**Comment by meker12** [comment]
@jrperritt   and @jamiehannaford  Just wondering if this PR can be merged yet.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-f96fb10879/docs/)

**Comment by jrperritt** [comment]
The content is ready to merge. I did notice, however, that the `Quickstart Guides` links in the left-side pane in staging aren't working. Maybe those pages don't exist in staging; I don't know.

**Comment by meker12** [comment]
I know we had a redirect for the QuickStart guide links. Not sure if that doesn't work in staging.  Will check it. Thx @jrperritt

**Pull request merged**
