### PR TITLE
[Don't merge yet - CLB v2 deploy postponed] Add Cloud Load Balancers v2 (EA) to landing page

### PR DESCRIPTION
**Pull request by cyrichardson**
Does not launch until 7/26 if CLB v2 (EA) launches on schedule this week, but please review @smashwilson or @meker12.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-9fc93cfbf6/docs/)

**Comment by meker12** [comment]
LGTM

**Comment by cyrichardson** [comment]
@meker12 Thanks for the review!

**Comment by cyrichardson** [comment]
The date for this launch has been delayed. As of today, 8/17/2016, I have not received notification of a new launch date from the CLB v2 PM.

**Comment by cyrichardson** [comment]
Closing this PR - due to deployment delayed with no new date for several months. Also, the landing page changes are now different for refactored API docs.

**Pull request closed without merging**
