### PR TITLE
Add v1.0 to Cloud Load Balancers heading on landing page in preparation

### PR DESCRIPTION
**Pull request by cyrichardson**
in preparation for addition of Cloud Load Balancers v2 (EA) next week. Cloud Load Balancers v2 (EA) will be a separate entry on the landing page beside CLB v1.0.

### CODE REVIEW

**Comment by cyrichardson** [comment]
@ktbartholomew or @smashwilson I seem to have broken the build with the change. When you have time, could one of you please provide assistance? Thanks!

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-05436a0802/docs/). :bow:

**Comment by smashwilson** [comment]
@cyrichardson: Not your fault; this was that race condition with Strider's GitHub provider and the `/merge` commit again. I redelivered the webhook and the build succeeded just fine.

**Comment by cyrichardson** [comment]
@ktbartholomew When you have time, could you please review and merge.

**Comment by cyrichardson** [comment]
@smashwilson Thanks a ton!

**Comment by ktbartholomew** [comment]
:shipit:

**Comment by cyrichardson** [comment]
@ktbartholomew Thanks so much for the review/merge!

**Pull request merged**
