### PR TITLE
Add examples for uploading files to subdirectories

### PR DESCRIPTION
**Pull request by carolynvs**
Closes https://github.com/rackerlabs/dxeng/issues/220

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-3e3e7d259c/docs/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-be827001aa/docs/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-dc3f9ac5ac/docs/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-16d22c381b/docs/). :bow:

**Comment by carolynvs** [comment]
Alrighty, the change can be found on the Cloud Files QuickStart guide, under "Upload objects to container", `/docs/cloud-files/quickstart/#upload-objects-to-container`.

**Comment by cyrichardson** [comment]
@carolynvs Your added text looks fine and aligns with the structure already in place for this documentation. But I'm sorry, I can speak to your code examples... no knowledge there for me! Perhaps you'll want to get someone else to check them out. Thanks again for adding this! It comes up with users a lot and this will help them a ton!

**Comment by carolynvs** [comment]
@cyrichardson The code samples are just copy/paste from the section above, and then I added the `{subdirectories}` prefix to the object name. So it's not new code really.

Thanks for the review!

**Pull request merged**
