### PR TITLE
Adding the rpc-vmware card and links

### PR DESCRIPTION
**Pull request by nimbinatus**
Makes the changes live on the landing site.

Please wait for Strider to provide a preview link before reviewing :)

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-fd65f82ffd/docs/).

**Comment by nimbinatus** [comment]
Hold off on reviews. I want to move it up to align with the other one.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-3bf0813b91/docs/)

**Comment by nimbinatus** [comment]
Ha, should be fixed now. Review away!

**Pull request merged**
