### PR TITLE
Update load balancer menu

### PR DESCRIPTION
**Pull request by meker12**
Update menu for refactored Dev Guide content

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-d93e04a388/docs/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-4c82dbb6d0/docs/)

**Comment by meker12** [comment]
@kmsholcomb Please review the most recent preview. Thx.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-37f85c1dba/docs/). :bow:

**Pull request merged**
