### PR TITLE
point More Information sections to developer.rackspace.com for API doc

### PR DESCRIPTION
**Pull request by rose-coste**
change product-specific Quickstarts to include  /_common/moreinfo.rst rather than repeating the same text in each source file

add inclusion of /_common/moreinfo.rst in Quickstarts where it was missing (CDN, Images, unused Identity)

in Quickstart for Auto Scale, correct heading levels so More Information section does not appear to be a subtopic of the Webhook section

----

This addresses issue https://github.com/rackerlabs/docs-quickstart/issues/59. 

Don't merge until @kmsholcomb can edit new draft of /_common/moreinfo.rst; changes there will appear in all QuickStarts when published.

### CODE REVIEW

**Comment by kmsholcomb** [comment]
Hi @rose-coste. The attached Word doc has my suggested markup for the common "More information" section. Please let me know if you have any questions. Thanks!

[More information_quickstart_editsKH.docx](https://github.com/rackerlabs/docs-quickstart/files/68653/More.information_quickstart_editsKH.docx)

**Comment by rose-coste** [comment]
Thanks, @kmsholcomb, I incorporated all your suggestions.

---rose

**Comment by rose-coste** [comment]
This PR is ready to merge but I no longer have write access here. Can someone else please merge this?

**Comment by smashwilson** [comment]
:shipit:

**Pull request merged**
